name: Bug report
description: Report something that is broken or unreliable
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide clear and precise information.
        Battery and background issues are often device-specific.

  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: "e.g. 0.9.2"
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android version
      placeholder: "e.g. Android 14"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & manufacturer
      placeholder: "e.g. Pixel 7 / Samsung Galaxy S22"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What did you expect, and what actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Enable high battery alert at 80%
        2. Plug in charger
        3. Wait until reaching 80%
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Logs, screenshots, or OEM battery settings info.
