name: Question
description: Ask a question about SureCharge
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Your question
    validations:
      required: true
